
spring:
  datasource:
    driver-class-name : org.h2.Driver
    url: jdbc:h2:mem:weatherdb
  h2:
    console:
      enabled: true
  config:
    import: optional:file:.env[.properties]
request:
  base-url: http://api.weatherstack.com/current
  access_key: ${API_KEY:default}
resilience4j:
  ratelimiter:
    instances:
      basic:
        limit-for-period: 10
        limit-refresh-period: 10m
        timeout-duration: 15s
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus